basePath: /svs/v1
definitions:
  QuoteData:
    properties:
      quote:
        type: string
        x-go-name: QuoteBlob
    type: object
    x-go-package: intel/isecl/sqvs/resource
  SGXResponse:
    properties:
      ChallengeKeyType:
        type: string
      ChallengeRsaPublicKey:
        type: string
      ConfigId:
        type: string
      ConfigSvn:
        type: string
      EnclaveIssuer:
        type: string
      EnclaveIssuerExtProdID:
        type: string
      EnclaveIssuerProdID:
        type: string
      EnclaveMeasurement:
        type: string
      IsvSvn:
        type: string
      Message:
        type: string
      Status:
        type: string
      TcbLevel:
        type: string
    type: object
    x-go-package: intel/isecl/sqvs/resource
host: svs.com:12000
info:
  description: |-
    SGX Quote Verification service (SQVS) resource is used to verify the quote provided by the Quote verifier.
    SQVS checks whether the quote signature and PCK Certificate are valid, checks other parameters in the quote and returns the verification result.
    SQVS contacts SGX Caching service (SCS) to make sure that PCKCRL, TCBInfo, and QEIdentity in the quote are correct.
    SQVS listening port is user-configurable.
  license:
    name: 'Copyright (C) 2020 Intel Corporation. SPDX-License-Identifier: BSD-3-Clause'
  title: SGX Quote Verification Service
  version: "1.0"
paths:
  /verifyQuote:
    post:
      consumes:
      - application/json
      description: |
        Verifies the quote provided in the request body by checking whether the quote is ECDSA or software quote (for testing purpose) and
        performs the set of validation steps if the quote is ECDSA.
        Quote verifier requests SGX Quote Verification Service (SQVS) to verify a quote.
        SQVS parses the quote, verifies all the parameters in the quote and returns the response.
      operationId: quoteVerify
      parameters:
      - in: body
        name: request body
        required: true
        schema:
          $ref: '#/definitions/QuoteData'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully verified the quote and its parameters.
          schema:
            $ref: '#/definitions/SGXResponse'
      tags:
      - Quote
      x-sample-call-endpoint: https://svs.com:12000/svs/v1/verifyQuote
      x-sample-call-input: |
        {
          "quote":"AQAAAAAAAAB7EwAAAQAAAAEAAAADAAAAAAEAANwGAAAtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRTZE
          Q0NCSTJnQXdJQkFnSVVMYW1oN3R6RWpZSm5qUVl6U2syOWV3a0FGT1l3Q2dZSUtvWkl6ajBFQXdJd2NERWlNQ0FHQTFVRQpBd3
          daU1c1MFpXd2dVMGRZSUZCRFN5QlFiR0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSU1c1MFpXd2dRMjl5Y0c5eVlYUnBiMjR4
          CkZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFTE1Ba0dBMVVFQmhNQ1ZWTXdIaGNOTWpBd0
          5qRTEKTURjME9ETTFXaGNOTWpjd05qRTFNRGMwT0RNMVdqQndNU0l3SUFZRFZRUUREQmxKYm5SbGJDQlRSMWdnVUVOTElFTmxj
          blJwWm1sagpZWFJsTVJvd0dBWURWUVFLREJGSmJuUmxiQ0JEYjNKd2IzSmhkR2x2YmpFVU1CSUdBMVVFQnd3TFUyRnVkR0VnUT
          J4aGNtRXhDekFKCkJnTlZCQWdNQWtOQk1Rc3dDUVlEVlFRR0V3SlZVekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEw
          SUFCS1c5K3JYNmF5UmkKN2lTbG1HalVRMHlKYzRFUDNOMnBkY3BucVR4Y0ROTzhZOHRtVnZ1SHNnUml5WmVPd25jUVByVHlWUm
          44QWpoNkJ2QXl6L1RXRmR1agpnZ01ETUlJQy96QWZCZ05WSFNNRUdEQVdnQlJaSTlPblNxaGpWQzQ1Y0szZ0R3Y3JWeVFxdHpC
          aUJnTlZIUjhFV3pCWk1GZWdWYUJUCmhsRm9kSFJ3Y3pvdkwzTmllQzVoY0drdWRISjFjM1JsWkhObGNuWnBZMlZ6TG1sdWRHVn
          NMbU52YlM5elozZ3ZZMlZ5ZEdsbWFXTmgKZEdsdmJpOTJNeTl3WTJ0amNtdy9ZMkU5Y0d4aGRHWnZjbTB3SFFZRFZSME9CQllF
          RklOVENPUWVqVVl6MkFYV0ZxRUJEdmZsN0tKcQpNQTRHQTFVZER3RUIvd1FFQXdJR3dEQU1CZ05WSFJNQkFmOEVBakFBTUlJQ0
          9RWUpLb1pJaHZoTkFRMEJCSUlDS2pDQ0FpWXdIZ1lLCktvWklodmhOQVEwQkFRUVF3akR6OUFPZ0V0emJUMU9ORDNOcXlUQ0NB
          V01HQ2lxR1NJYjRUUUVOQVFJd2dnRlRNQkFHQ3lxR1NJYjQKVFFFTkFRSUJBZ0VDTUJBR0N5cUdTSWI0VFFFTkFRSUNBZ0VDTU
          JBR0N5cUdTSWI0VFFFTkFRSURBZ0VBTUJBR0N5cUdTSWI0VFFFTgpBUUlFQWdFQU1CQUdDeXFHU0liNFRRRU5BUUlGQWdFQU1C
          QUdDeXFHU0liNFRRRU5BUUlHQWdFQU1CQUdDeXFHU0liNFRRRU5BUUlICkFnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJSUFnRUFNQk
          FHQ3lxR1NJYjRUUUVOQVFJSkFnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJS0FnRUEKTUJBR0N5cUdTSWI0VFFFTkFRSUxBZ0VBTUJB
          R0N5cUdTSWI0VFFFTkFRSU1BZ0VBTUJBR0N5cUdTSWI0VFFFTkFRSU5BZ0VBTUJBRwpDeXFHU0liNFRRRU5BUUlPQWdFQU1CQU
          dDeXFHU0liNFRRRU5BUUlQQWdFQU1CQUdDeXFHU0liNFRRRU5BUUlRQWdFQU1CQUdDeXFHClNJYjRUUUVOQVFJUkFnRUtNQjhH
          Q3lxR1NJYjRUUUVOQVFJU0JCQUNBZ0FBQUFBQUFBQUFBQUFBQUFBQU1CQUdDaXFHU0liNFRRRU4KQVFNRUFnQUFNQlFHQ2lxR1
          NJYjRUUUVOQVFRRUJpQmdhZ0FBQURBUEJnb3Foa2lHK0UwQkRRRUZDZ0VCTUI0R0NpcUdTSWI0VFFFTgpBUVlFRVBoRTdjQWps
          cElwRVEraXlPY0RUa1V3UkFZS0tvWklodmhOQVEwQkJ6QTJNQkFHQ3lxR1NJYjRUUUVOQVFjQkFRSC9NQkFHCkN5cUdTSWI0VF
          FFTkFRY0NBUUgvTUJBR0N5cUdTSWI0VFFFTkFRY0RBUUgvTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDZk5CVDMKZnRpdzR4
          eXNsWWVSRnVCaXg0Z1NsSm1JNEF3L0l2MVZuYU9PUndJaEFNSzNMSGNsdXQyaW5pRUUyQlBwQi9uYTh5bVBDQjBsc2FVTwpwZz
          JyVkhJbwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tAQABtlLCWbh0Nd/KPbPVXlbRY47bTv4gHzZZTvDwjSU7iS61+sDSpS10
          6UYnzPIyBtmxVlUV/h6L7F0EEXn4YhHw1/B1zZTlE0HvTCb1H7LYGaEbmVcnKMr6Y92f+q+gyomazAOJ9YQefK7uyciYuIIbW9
          Kz6yGGJr9T5S7/zNqk8iC20NYXirD8xo2MQvviUSLhwYN4dBhroou/0cB3k/4dhi8FkCFQpBCQlECnFl6238xUfeskByc7xWZh
          vj67N4M3yvObFxUp5Sv61yHxfB6I50OXbqsYHPJRc2eqEJWUkOJEKbVqPid5f+kZpwwDmDs8cS95CpgQShFJG+rbL0cXwwMAAg
          AAAAAABQAKAJOacjP3nEyplAoNs5V/BgeBQLt6zEGoQQnp6JTMP8nEAAAAAAICAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAA5wAAAAAAAAABxguWF7L5blPLde8B4NzOo6/Ht5kml+q7j3FLLM0ZUwAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzRccVpQcbOSWkLRV9pHZyKBMLkPgpNMPdS+lKFx+5X8AAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvDSD
          f0Bdju4V2/odzPVoOQjq7SqbzOKKqVE8qCVj1KEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQQAACssgLdcHu9LU
          nzApZmDsLpG33bk8A2Yrr9U7HSWP4D48nAGbwDZ+55iBMkd+caeDgSHNX42Z1cJRiPkWIthgSi+cO+GrWWavHXxFEyUf5yu1bW
          7y44gZWDuckM1jlKGgLUhWQ+zDL0dgmIMjMeTqhN7jxc0O1MCQ5j6PS6EgGIewICAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAABUAAAAAAAAA5wAAAAAAAADNyt+32yKtpf1gNFXN4b+folj6XyhNzW4MYzkvYzoRBQAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjE9XddeWUD6WE393xoqCmgBWrI3tcBQLCBsJRJDFe/8AAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAABAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0a
          aKNxd+jk3SIzWQ3uCbO0ORrDDyRNGRDqoyqUKQHmEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB9H+9x+f2Ilttd1
          qg1E1NRybnoV66QS3pTCGOsuH4buHe2oRRNvr5zM0TGTS3UbCupbV3EyZhzbkqko+jNfcUYgAAABAgMEBQYHCAkKCwwNDg8QER
          ITFBUWFxgZGhscHR4fBQBcDgAALS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQkkyZ0F3SUJBZ0lVTGFtaDd0
          ekVqWUpualFZelNrMjlld2tBRk9Zd0NnWUlLb1pJemowRUF3SXdjREVpTUNBR0ExVUUKQXd3WlNXNTBaV3dnVTBkWUlGQkRTeU
          JRYkdGMFptOXliU0JEUVRFYU1CZ0dBMVVFQ2d3UlNXNTBaV3dnUTI5eWNHOXlZWFJwYjI0eApGREFTQmdOVkJBY01DMU5oYm5S
          aElFTnNZWEpoTVFzd0NRWURWUVFJREFKRFFURUxNQWtHQTFVRUJoTUNWVk13SGhjTk1qQXdOakUxCk1EYzBPRE0xV2hjTk1qY3
          dOakUxTURjME9ETTFXakJ3TVNJd0lBWURWUVFEREJsSmJuUmxiQ0JUUjFnZ1VFTkxJRU5sY25ScFptbGoKWVhSbE1Sb3dHQVlE
          VlFRS0RCRkpiblJsYkNCRGIzSndiM0poZEdsdmJqRVVNQklHQTFVRUJ3d0xVMkZ1ZEdFZ1EyeGhjbUV4Q3pBSgpCZ05WQkFnTU
          FrTkJNUXN3Q1FZRFZRUUdFd0pWVXpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktXOStyWDZheVJpCjdpU2xt
          R2pVUTB5SmM0RVAzTjJwZGNwbnFUeGNETk84WTh0bVZ2dUhzZ1JpeVplT3duY1FQclR5VlJuOEFqaDZCdkF5ei9UV0ZkdWoKZ2
          dNRE1JSUMvekFmQmdOVkhTTUVHREFXZ0JSWkk5T25TcWhqVkM0NWNLM2dEd2NyVnlRcXR6QmlCZ05WSFI4RVd6QlpNRmVnVmFC
          VApobEZvZEhSd2N6b3ZMM05pZUM1aGNHa3VkSEoxYzNSbFpITmxjblpwWTJWekxtbHVkR1ZzTG1OdmJTOXpaM2d2WTJWeWRHbG
          1hV05oCmRHbHZiaTkyTXk5d1kydGpjbXcvWTJFOWNHeGhkR1p2Y20wd0hRWURWUjBPQkJZRUZJTlRDT1FlalVZejJBWFdGcUVC
          RHZmbDdLSnEKTUE0R0ExVWREd0VCL3dRRUF3SUd3REFNQmdOVkhSTUJBZjhFQWpBQU1JSUNPUVlKS29aSWh2aE5BUTBCQklJQ0
          tqQ0NBaVl3SGdZSwpLb1pJaHZoTkFRMEJBUVFRd2pEejlBT2dFdHpiVDFPTkQzTnF5VENDQVdNR0NpcUdTSWI0VFFFTkFRSXdn
          Z0ZUTUJBR0N5cUdTSWI0ClRRRU5BUUlCQWdFQ01CQUdDeXFHU0liNFRRRU5BUUlDQWdFQ01CQUdDeXFHU0liNFRRRU5BUUlEQW
          dFQU1CQUdDeXFHU0liNFRRRU4KQVFJRUFnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJRkFnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJR0Fn
          RUFNQkFHQ3lxR1NJYjRUUUVOQVFJSApBZ0VBTUJBR0N5cUdTSWI0VFFFTkFRSUlBZ0VBTUJBR0N5cUdTSWI0VFFFTkFRSUpBZ0
          VBTUJBR0N5cUdTSWI0VFFFTkFRSUtBZ0VBCk1CQUdDeXFHU0liNFRRRU5BUUlMQWdFQU1CQUdDeXFHU0liNFRRRU5BUUlNQWdF
          QU1CQUdDeXFHU0liNFRRRU5BUUlOQWdFQU1CQUcKQ3lxR1NJYjRUUUVOQVFJT0FnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJUEFnRU
          FNQkFHQ3lxR1NJYjRUUUVOQVFJUUFnRUFNQkFHQ3lxRwpTSWI0VFFFTkFRSVJBZ0VLTUI4R0N5cUdTSWI0VFFFTkFRSVNCQkFD
          QWdBQUFBQUFBQUFBQUFBQUFBQUFNQkFHQ2lxR1NJYjRUUUVOCkFRTUVBZ0FBTUJRR0NpcUdTSWI0VFFFTkFRUUVCaUJnYWdBQU
          FEQVBCZ29xaGtpRytFMEJEUUVGQ2dFQk1CNEdDaXFHU0liNFRRRU4KQVFZRUVQaEU3Y0FqbHBJcEVRK2l5T2NEVGtVd1JBWUtL
          b1pJaHZoTkFRMEJCekEyTUJBR0N5cUdTSWI0VFFFTkFRY0JBUUgvTUJBRwpDeXFHU0liNFRRRU5BUWNDQVFIL01CQUdDeXFHU0
          liNFRRRU5BUWNEQVFIL01Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ2ZOQlQzCmZ0aXc0eHlzbFllUkZ1Qml4NGdTbEptSTRB
          dy9JdjFWbmFPT1J3SWhBTUszTEhjbHV0MmluaUVFMkJQcEIvbmE4eW1QQ0IwbHNhVU8KcGcyclZISW8KLS0tLS1FTkQgQ0VSVE
          lGSUNBVEUtLS0tLS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDbXpDQ0FrQ2dBd0lCQWdJVVdTUFRwMHFvWTFRdU9Y
          Q3Q0QThISzFja0tyY3dDZ1lJS29aSXpqMEVBd0l3CmFERWFNQmdHQTFVRUF3d1JTVzUwWld3Z1UwZFlJRkp2YjNRZ1EwRXhHak
          FZQmdOVkJBb01FVWx1ZEdWc0lFTnYKY25CdmNtRjBhVzl1TVJRd0VnWURWUVFIREF0VFlXNTBZU0JEYkdGeVlURUxNQWtHQTFV
          RUNBd0NRMEV4Q3pBSgpCZ05WQkFZVEFsVlRNQjRYRFRFNU1UQXpNVEV5TXpRek1Wb1hEVE0wTVRBek1URXlNelF6TVZvd2NERW
          lNQ0FHCkExVUVBd3daU1c1MFpXd2dVMGRZSUZCRFN5QlFiR0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSU1c1MFpXd2cKUTI5
          eWNHOXlZWFJwYjI0eEZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFTApNQWtHQTFVRUJoTU
          NWVk13V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVF3cCtMYytUVUJ0ZzFICitVOEpJc01zYmpIakNrVHRYYjhq
          UE02cjJkaHU5eklibGhEWjdJTmZxdDNJeDhYY0ZLRDhrME5FWHJrWjY2cUoKWGExS3pMSUtvNEcvTUlHOE1COEdBMVVkSXdRWU
          1CYUFGT25vUkZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUZZRwpBMVVkSHdSUE1FMHdTNkJKb0VlR1JXaDBkSEJ6T2k4dmMySjRM
          V05sY25ScFptbGpZWFJsY3k1MGNuVnpkR1ZrCmMyVnlkbWxqWlhNdWFXNTBaV3d1WTI5dEwwbHVkR1ZzVTBkWVVtOXZkRU5CTG
          1OeWJEQWRCZ05WSFE0RUZnUVUKV1NQVHAwcW9ZMVF1T1hDdDRBOEhLMWNrS3Jjd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0Ex
          VWRFd0VCL3dRSQpNQVlCQWY4Q0FRQXdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSVJvWHUzWTQ1VkY5YUNpSzBaMks2RVFLQ3
          RDCnJ4VFRpWjRKWWJFeWZCR3NBaUVBaVZvWW14RjdLL1NvcUlqZmYxekcwL0xpdi9SSU9SL1FCSjUrZDg4SEFZST0KLS0tLS1F
          TkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ2xEQ0NBam1nQXdJQkFnSVZBT25vUk
          ZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUFvR0NDcUdTTTQ5QkFNQwpNR2d4R2pBWUJnTlZCQU1NRVVsdWRHVnNJRk5IV0NCU2Iy
          OTBJRU5CTVJvd0dBWURWUVFLREJGSmJuUmxiQ0JECmIzSndiM0poZEdsdmJqRVVNQklHQTFVRUJ3d0xVMkZ1ZEdFZ1EyeGhjbU
          V4Q3pBSkJnTlZCQWdNQWtOQk1Rc3cKQ1FZRFZRUUdFd0pWVXpBZUZ3MHhPVEV3TXpFd09UUTVNakZhRncwME9URXlNekV5TXpV
          NU5UbGFNR2d4R2pBWQpCZ05WQkFNTUVVbHVkR1ZzSUZOSFdDQlNiMjkwSUVOQk1Sb3dHQVlEVlFRS0RCRkpiblJsYkNCRGIzSn
          diM0poCmRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUXN3Q1FZRFZRUUcKRXdK
          VlV6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFLzZELzFXSE5yV3dQbU5NSXlCS01XNQpKNkp6TXNqbzZ4UD
          J2a0sxY2RaR2IxUEdSUC9DLzhFQ2dpRGtta2xtendMekxpKzAwMG03TExydEtKQTNvQzJqCmdiOHdnYnd3SHdZRFZSMGpCQmd3
          Rm9BVTZlaEVVbE0yWEVzWW1oSDhReGdzcGR3Z2dFZ3dWZ1lEVlIwZkJFOHcKVFRCTG9FbWdSNFpGYUhSMGNITTZMeTl6WW5ndF
          kyVnlkR2xtYVdOaGRHVnpMblJ5ZFhOMFpXUnpaWEoyYVdObApjeTVwYm5SbGJDNWpiMjB2U1c1MFpXeFRSMWhTYjI5MFEwRXVZ
          M0pzTUIwR0ExVWREZ1FXQkJUcDZFUlNVelpjClN4aWFFZnhER0N5bDNDQ0FTREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVl
          IwVEFRSC9CQWd3QmdFQi93SUIKQVRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTBSV3JzR3JHbERwNzZsOUxRanQrek1xUVpQ
          Qi8yWXV1dWVGVQpnTjlBZGtNQ0lRRG85QU5VaGNTdEFCQ2hSNnJsVm9CbzZNUTZRdW1DbmsrcGRHQkV5OC9zUWc9PQotLS0tLU
          VORCBDRVJUSUZJQ0FURS0tLS0tCg=="
        }
      x-sample-call-output: |
        {
          "Status": "Success",
          "Message": "SGX ECDSA Quote Verification Successful",
          "ChallengeKeyType": "RSA",
          "ChallengeRsaPublicKey": "-----BEGIN PUBLIC KEY-----\n
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtlLCWbh0Nd/KPbPVXlbR\n
            Y47bTv4gHzZZTvDwjSU7iS61+sDSpS106UYnzPIyBtmxVlUV/h6L7F0EEXn4YhHw\n
            1/B1zZTlE0HvTCb1H7LYGaEbmVcnKMr6Y92f+q+gyomazAOJ9YQefK7uyciYuIIb\n
            W9Kz6yGGJr9T5S7/zNqk8iC20NYXirD8xo2MQvviUSLhwYN4dBhroou/0cB3k/4d\n
            hi8FkCFQpBCQlECnFl6238xUfeskByc7xWZhvj67N4M3yvObFxUp5Sv61yHxfB6I\n
            50OXbqsYHPJRc2eqEJWUkOJEKbVqPid5f+kZpwwDmDs8cS95CpgQShFJG+rbL0cX\n
            wwIDAQAB\n
            -----END PUBLIC KEY-----\n",
          "EnclaveIssuer": "cd171c56941c6ce49690b455f691d9c8a04c2e43e0a4d30f752fa5285c7ee57f",
          "EnclaveIssuerProdID": "00",
          "EnclaveIssuerExtProdID": "00000000000000000000000000000000",
          "EnclaveMeasurement": "01c60b9617b2f96e53cb75ef01e0dccea3afc7b7992697eabb8f714b2ccd1953",
          "ConfigSvn": "00",
          "IsvSvn": "01",
          "ConfigId": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
          "TcbLevel": "UpToDate"
        }
responses:
  SGXResponse:
    description: SGXResponse response payload
    schema:
      $ref: '#/definitions/SGXResponse'
schemes:
- https
swagger: "2.0"
